### ISSUE TITLE
[주제 제안] Random Shuffling Trick

### ISSUE THREAD

**Issue by kimjg1119** [algoshitpo/algoshitpo.github.io#13]
### 주제 이름
* Random Shuffling Trick
### 주제 소개 (관련 자료 링크 포함)
적당히 자료를 처리하는 순서를 무작위로 섞어서 커팅하면, 시간복잡도랑 상수를 상당히 낮출 수 있다는 경우가 있다고 함. 그런 경우들을 소개하고 있음.
가능하면 이런 경우에 속하는 어려운 문제를 따로 하나 찾아서 같이 포스팅해줬으면 좋겠다
### 대략적인 난이도
* 개념 매우 쉬움, CF 민트도 이해 및 응용 가능
* 최대한 다양한 문제에 대해 예시를 들어주면 좋겠다
### 관련 문제 링크
* https://codeforces.com/contest/442/problem/E

**Comment by leejseo** [comment]
random shuffling의 활용 예) Finding smallest enclosing circle in linear time
http://www.secmem.org/blog/2019/04/08/Smallest-Enclosing-Circle/

**Comment by leejseo** [comment]
관련 내용 제안) worst-case complexity가 아닌 average-case complexity는 어떤 방법으로 분석할 수 있는가?
- 예시: 퀵소트가 평균적으로 O(n log n) 시간에 작동함에 대한 증명(?)

**Comment by kimjg1119** [comment]
> 관련 내용 제안) worst-case complexity가 아닌 average-case complexity는 어떤 방법으로 분석할 수 있는가?
> 
> * 예시: 퀵소트가 평균적으로 O(n log n) 시간에 작동함에 대한 증명(?)

주제 풀에 있는 Potential Method하고는 다른 영역?

**Comment by leejseo** [comment]
> 주제 풀에 있는 Potential Method하고는 다른 영역?
매우 명확하게 다르죠. Random shuffling trick의 정당성을 설명하는 영역이라 보시면 됩니다.

**Comment by leejseo** [comment]
다만 퀵소트가 좋은 예시는 아니었던 것 같네요.

**Comment by justiceHui** [comment]
https://algoshitpo.github.io/2020/03/23/random/
